CREATE TABLE IF NOT EXISTS mpa
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         varchar                                          NOT NULL,
    description  varchar DEFAULT NULL,
    release_date timestamp                                        NOT NULL,
    duration     integer                                          NOT NULL,
    mpa_id       bigint                                          NOT NULL
);

CREATE TABLE IF NOT EXISTS friends
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id1 bigint                                          NOT NULL,
    user_id2 bigint                                          NOT NULL,
    status   tinyint DEFAULT false
);

CREATE TABLE IF NOT EXISTS genre
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar                                              NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    film_id  bigint                                              NOT NULL,
    genre_id bigint                                              NOT NULL
);

CREATE TABLE IF NOT EXISTS enjoy
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id bigint                                          NOT NULL,
    film_id bigint                                          NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email    varchar                                              NOT NULL,
    login    varchar                                              NOT NULL,
    name     varchar   DEFAULT NULL,
    birthday timestamp DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS directors
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar                                              NOT NULL
);

CREATE TABLE IF NOT EXISTS film_director
(
    film_id     bigint NOT NULL,
    director_id bigint NOT NULL,

    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_feed
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    entity_id       bigint               NOT NULL,
    user_id         bigint               NOT NULL,
    timestamp       bigint               NOT NULL,
    event_type      varchar(10) NOT NULL,
    event_operation varchar(10) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

create table IF NOT EXISTS reviews
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    content     varchar(255) NOT NULL,
    is_positive boolean                NOT NULL,
    user_id     bigint                NOT NULL,
    film_id     bigint                NOT NULL,
    useful      integer default 0      NOT NULL,
        FOREIGN KEY (film_id) references films (id)
            ON DELETE CASCADE,
        FOREIGN KEY (user_id) references users (id)
            ON DELETE CASCADE
);
create table IF NOT EXISTS review_likes
(
    review_id bigint NOT NULL,
    is_like   boolean NOT NULL,
    user_id   bigint NOT NULL,
        FOREIGN KEY (review_id) references reviews (id)
            ON DELETE CASCADE,
        FOREIGN KEY (user_id) references users (id)
            ON DELETE CASCADE
);


ALTER TABLE enjoy
    ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE enjoy
    ADD FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;

ALTER TABLE friends
    ADD FOREIGN KEY (user_id1) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE friends
    ADD FOREIGN KEY (user_id2) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE films
    ADD FOREIGN KEY (mpa_id) REFERENCES mpa (id);

ALTER TABLE film_genres
    ADD FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE film_genres
    ADD FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;
